/* SMEAG StudyGround — tools/build_set3.mjs : SET 3 source docx files -> assets/set3.js.
   세트 만들기 관문은 ../../docs/set-build.md 에 있다.

   build_set12.mjs 와 다른 것 하나 — stop 에서 멈추지 않는다. 세트는 부족해도 항상 짓고
   (2026-09-15 지시), 안 된 것은 tools/set_report.mjs 가 docs/set-reports/set3.md 에 적는다.
   정답이 성립하지 않은 문항은 팩에 unscored 로 남아 점수에서 빠진다.
   원본 이름은 source_docs.mjs 가 고른다(SET 3 스크립트는 'TEST 2 SCRIPT 2.docx' 로 왔다). */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { sourceDirs, findSourceDocsIn } from './source_docs.mjs';
import { writeSetReport } from './set_report.mjs';

const require = createRequire(import.meta.url);
const SG2 = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const DOCX = require(path.join(SG2, 'assets/docx-read.js'));
const IMPORT = require(path.join(SG2, 'assets/set-import.js'));

const SET_NO = 3;
const IMPORTED_AT = '2026-09-22T00:00:00.000Z';

const FOUND = findSourceDocsIn(sourceDirs(SG2), SET_NO);
const FILES = { questions: FOUND.questions, script: FOUND.script, answers: FOUND.answers };

async function read(name) {
  const b = fs.readFileSync(path.join(FOUND.dir, name));
  return DOCX.read(b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength));
}

/* 문서 밖 자료(듣기 화자 사진 · 토론 얼굴)는 있으면 붙이고, 없으면 리포트에 적는다. */
function optionalJson(rel) {
  const p = path.join(SG2, rel);
  return fs.existsSync(p) ? JSON.parse(fs.readFileSync(p, 'utf8')) : undefined;
}

const questions = await read(FILES.questions);
const script = await read(FILES.script);
const answers = await read(FILES.answers);

const out = IMPORT.build({
  code: 'SET 3', questions, script, answers,
  listeningImages: optionalJson('config/set3-listening-images.json'),
  discussionImages: optionalJson('config/set3-writing-images.json'),
  strictSource: true
});
if (!out.pack) {
  out.gates.forEach((g) => console.error(g.level + ' [' + g.scope + '] ' + g.message));
  process.exit(1);   /* 문제지를 읽지도 못했다 — 지을 것이 없다 */
}

const pack = out.pack;
pack.importedAt = IMPORTED_AT;
if (pack.summary) pack.summary.sources = [FILES.questions, FILES.script, FILES.answers];

fs.writeFileSync(
  path.join(SG2, 'assets/set3.js'),
  '/* Generated by tools/build_set3.mjs (same code path as admin-set-import.html).\n'
    + '   Do not edit by hand — fix the document and build again. */\n'
    + 'window.SMEAG_SET3 = ' + JSON.stringify(pack, null, 2) + ';\n\n'
    + "if (window.SG_SET_IMPORT && typeof window.SG_SET_IMPORT.withHelpers === 'function') {\n"
    + '  window.SG_SET_IMPORT.withHelpers(window.SMEAG_SET3);\n'
    + '}\n'
);

const picDir = path.join(SG2, 'media/pictures/set3');
fs.mkdirSync(picDir, { recursive: true });
let pics = 0;
for (const name of Object.keys(questions.media || {})) {
  fs.writeFileSync(path.join(picDir, name.split('/').pop()), Buffer.from(questions.media[name]));
  pics++;
}

const rep = writeSetReport({ setNo: SET_NO, sg2: SG2, out, sources: pack.summary.sources });

console.log('assets/set3.js — ' + out.stats.total + ' questions '
  + JSON.stringify(out.stats.bySection) + ', ' + pics + ' pictures');
console.log('sources: ' + FOUND.dir + '\n  ' + [FILES.questions, FILES.script, FILES.answers].join('\n  '));
console.log('report: ' + path.relative(path.dirname(path.dirname(SG2)), rep.file) + ' ' + JSON.stringify(rep.counts));
