/* SMEAG StudyGround — tools/build_set11.mjs : SET 11 source docx files -> assets/set11.js. */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const SG2 = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ROOT = path.resolve(SG2, '../../..');
const SOURCE_ROOT = path.join(ROOT, 'kenneth-brain/smeag-TOFEL 자료');

const DOCX = require(path.join(SG2, 'assets/docx-read.js'));
const IMPORT = require(path.join(SG2, 'assets/set-import.js'));

const FILES = {
  questions: 'NEW TOEFL SET 11.docx',
  script: 'SET 11 SCRIPT.docx',
  answers: 'SET 11 ANWER KEY.docx',
};

const IMPORTED_AT = '2026-09-02T00:00:00.000Z';

async function read(name) {
  const b = fs.readFileSync(path.join(SOURCE_ROOT, name));
  return DOCX.read(b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength));
}

const questions = await read(FILES.questions);
const script = await read(FILES.script);
const answers = await read(FILES.answers);

const out = IMPORT.build({ code: 'SET 11', questions, script, answers });
const stop = out.gates.filter((g) => g.level === 'stop');
if (stop.length) {
  stop.forEach((g) => console.error('STOP [' + g.scope + '] ' + g.message));
  process.exit(1);
}
out.gates.forEach((g) => console.warn('warn [' + g.scope + '] ' + g.message));

const pack = out.pack;
pack.importedAt = IMPORTED_AT;
if (pack.summary) pack.summary.sources = [FILES.questions, FILES.script, FILES.answers];

fs.writeFileSync(
  path.join(SG2, 'assets/set11.js'),
  '/* Generated by tools/build_set11.mjs (same code path as admin-set-import.html).\n'
    + '   Do not edit by hand — fix the document and build again. */\n'
    + 'window.SMEAG_SET11 = ' + JSON.stringify(pack, null, 2) + ';\n\n'
    + "if (window.SG_SET_IMPORT && typeof window.SG_SET_IMPORT.withHelpers === 'function') {\n"
    + '  window.SG_SET_IMPORT.withHelpers(window.SMEAG_SET11);\n'
    + '}\n'
);

const picDir = path.join(SG2, 'media/pictures/set11');
fs.mkdirSync(picDir, { recursive: true });
let pics = 0;
for (const name of Object.keys(questions.media || {})) {
  fs.writeFileSync(path.join(picDir, name.split('/').pop()), Buffer.from(questions.media[name]));
  pics++;
}

console.log('assets/set11.js — ' + out.stats.total + ' questions '
  + JSON.stringify(out.stats.bySection) + ', ' + pics + ' pictures');
