/* SMEAG StudyGround — tools/build_set11.mjs : SET 11 source docx files -> assets/set11.js.
   세트 만들기 네 관문(원본 그대로 · 음성 대조 · 정답 크로스체크 · 저장 검산)은
   ../../docs/set-build.md 에 있다. 여기서는 첫 관문과 셋째 관문이 gate 로 걸린다. */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const SG2 = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ROOT = path.resolve(SG2, '../../..');
const SOURCE_ROOT = path.join(ROOT, 'kenneth-brain/smeag-TOFEL 자료');

const DOCX = require(path.join(SG2, 'assets/docx-read.js'));
const IMPORT = require(path.join(SG2, 'assets/set-import.js'));

const FILES = {
  questions: 'NEW TOEFL SET 11.docx',
  script: 'SET 11 SCRIPT.docx',
  answers: 'SET 11 ANWER KEY.docx',
};

const IMPORTED_AT = '2026-09-02T00:00:00.000Z';

async function read(name) {
  const b = fs.readFileSync(path.join(SOURCE_ROOT, name));
  return DOCX.read(b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength));
}

const questions = await read(FILES.questions);
const script = await read(FILES.script);
const answers = await read(FILES.answers);

/* strictSource — 관리자 화면(admin-set-import.html)과 같은 잣대로 짓는다. 이게 없으면
   명령줄로 지은 팩만 조용히 느슨해진다: 문서에 없는 보기·정답에서 역산한 타일이
   들어간 채로 assets/set<N>.js 에 박히고, 그건 화면에서는 저장조차 막히는 팩이다. */
/* 듣기 화면의 화자 사진 — 배역 매니페스트(tts-voices-set11exam-11labs.json)를 보고
   목소리 성별·인원에 맞춘 것이다. 이게 없으면 듣기 1·2 모듈만 사진 없이 뜬다. */
const listeningImages = JSON.parse(fs.readFileSync(path.join(SG2, 'config/set11-listening-images.json'), 'utf8'));

const out = IMPORT.build({ code: 'SET 11', questions, script, answers, listeningImages, strictSource: true });
const stop = out.gates.filter((g) => g.level === 'stop');
if (stop.length) {
  stop.forEach((g) => console.error('STOP [' + g.scope + '] ' + g.message));
  process.exit(1);
}
out.gates.forEach((g) => console.warn('warn [' + g.scope + '] ' + g.message));

const pack = out.pack;
pack.importedAt = IMPORTED_AT;
if (pack.summary) pack.summary.sources = [FILES.questions, FILES.script, FILES.answers];

fs.writeFileSync(
  path.join(SG2, 'assets/set11.js'),
  '/* Generated by tools/build_set11.mjs (same code path as admin-set-import.html).\n'
    + '   Do not edit by hand — fix the document and build again. */\n'
    + 'window.SMEAG_SET11 = ' + JSON.stringify(pack, null, 2) + ';\n\n'
    + "if (window.SG_SET_IMPORT && typeof window.SG_SET_IMPORT.withHelpers === 'function') {\n"
    + '  window.SG_SET_IMPORT.withHelpers(window.SMEAG_SET11);\n'
    + '}\n'
);

const picDir = path.join(SG2, 'media/pictures/set11');
fs.mkdirSync(picDir, { recursive: true });
let pics = 0;
for (const name of Object.keys(questions.media || {})) {
  fs.writeFileSync(path.join(picDir, name.split('/').pop()), Buffer.from(questions.media[name]));
  pics++;
}

console.log('assets/set11.js — ' + out.stats.total + ' questions '
  + JSON.stringify(out.stats.bySection) + ', ' + pics + ' pictures');
