/* SMEAG StudyGround — tools/build_set10.mjs : SET 10 원본 docx 3종 → assets/set10.js.
 *
 * 왜 있는가
 *   admin-set-import.html 이 브라우저에서 하는 일과 **같은 코드**(assets/docx-read.js ·
 *   assets/set-import.js)를 터미널에서 돌린다. 가져오기 화면은 팩을 localStorage 에 두므로
 *   그 브라우저 밖으로 나가지 않는다 — 배포된 사이트가 SET 10 을 열려면 set9.js 처럼
 *   저장소에 커밋된 파일이어야 한다. 그래서 굽는 자리를 하나 만들었다.
 *
 * 무엇을 만드는가
 *   assets/set10.js            window.SMEAG_SET10 = {...}  (exam-shell.js 가 ?set=set10 에 싣는다)
 *   media/pictures/set10/*.png 문항 docx 안의 삽화 10장 (팩이 이 경로로 가리킨다)
 *
 * 쓰는 법:  node studyground/sg2/tools/build_set10.mjs
 * 오디오(media/audio/set10/*.mp3 40장)는 여기서 만들지 않는다 — tools/make_set_audio.sh 의 몫이다.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const SG2 = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ROOT = path.resolve(SG2, '../..');            // 저장소 뿌리 — 원본 docx 가 있는 곳

const DOCX = require(path.join(SG2, 'assets/docx-read.js'));
const IMPORT = require(path.join(SG2, 'assets/set-import.js'));

const FILES = {
  questions: 'NEW TOEFL MOCK TEST SET 10 Questions.docx',
  script: 'SET 10 SCRIPT.docx',
  answers: 'SET 10 ANSWER KEY.docx',
};

/* 팩에 박히는 시각은 고정한다 — 다시 구울 때마다 diff 가 나면 안 된다. */
const IMPORTED_AT = '2026-08-18T00:00:00.000Z';

async function read(name) {
  const b = fs.readFileSync(path.join(ROOT, name));
  return DOCX.read(b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength));
}

const questions = await read(FILES.questions);
const script = await read(FILES.script);
const answers = await read(FILES.answers);
const listeningImages = JSON.parse(fs.readFileSync(path.join(SG2, 'config/set10-listening-images.json'), 'utf8'));

const out = IMPORT.build({ code: 'SET 10', questions, script, answers, listeningImages });
const stop = out.gates.filter((g) => g.level === 'stop');
if (stop.length) {
  stop.forEach((g) => console.error('STOP [' + g.scope + '] ' + g.message));
  process.exit(1);                                   // 시험을 못 만드는 문제는 조용히 넘기지 않는다
}
out.gates.forEach((g) => console.warn('warn [' + g.scope + '] ' + g.message));

const pack = out.pack;
pack.importedAt = IMPORTED_AT;
if (pack.summary) pack.summary.sources = [FILES.questions, FILES.script, FILES.answers];

fs.writeFileSync(
  path.join(SG2, 'assets/set10.js'),
  '/* Generated by tools/build_set10.mjs (same code path as admin-set-import.html).\n'
    + '   Do not edit by hand — fix the document and build again. */\n'
    + 'window.SMEAG_SET10 = ' + JSON.stringify(pack, null, 2) + ';\n\n'
    + "if (window.SG_SET_IMPORT && typeof window.SG_SET_IMPORT.withHelpers === 'function') {\n"
    + '  window.SG_SET_IMPORT.withHelpers(window.SMEAG_SET10);\n'
    + '}\n'
);

/* 그림은 팩과 따로 간다. 업로드로 만든 세트는 IndexedDB(set-media.js)에 들어가지만
   커밋된 세트는 저장소 파일이고, set-media.js 는 저장된 것이 없으면 이 경로로 떨어진다. */
const picDir = path.join(SG2, 'media/pictures/set10');
fs.mkdirSync(picDir, { recursive: true });
let pics = 0;
for (const name of Object.keys(questions.media || {})) {
  fs.writeFileSync(path.join(picDir, name.split('/').pop()), Buffer.from(questions.media[name]));
  pics++;
}

console.log('assets/set10.js — ' + out.stats.total + ' questions '
  + JSON.stringify(out.stats.bySection) + ', ' + pics + ' pictures');
