/* SMEAG StudyGround — tools/build_set12.mjs : SET 12 source docx files -> assets/set12.js.
   세트 만들기 다섯 관문(원본 그대로 · 음성 대조 · 정답 크로스체크 · 저장 검산 · 완결성)은
   ../../docs/set-build.md 에 있다. 여기서는 첫 관문과 셋째 관문이 gate 로 걸린다.

   build_set11.mjs 와 다른 것 하나 — 원본 세 장의 이름을 적어 두지 않는다.
   이름은 세트마다 달라서(SET 11·12 는 'ANWER KEY' 오타다) 적어 둔 도구는 다음 세트에서
   멈춘다. tools/source_docs.mjs 가 폴더를 읽어 고른다. */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { sourceDirs, findSourceDocsIn } from './source_docs.mjs';

const require = createRequire(import.meta.url);
const SG2 = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const DOCX = require(path.join(SG2, 'assets/docx-read.js'));
const IMPORT = require(path.join(SG2, 'assets/set-import.js'));

const SET_NO = 12;
const IMPORTED_AT = '2026-09-04T00:00:00.000Z';

const FOUND = findSourceDocsIn(sourceDirs(SG2), SET_NO);
const FILES = { questions: FOUND.questions, script: FOUND.script, answers: FOUND.answers };

async function read(name) {
  const b = fs.readFileSync(path.join(FOUND.dir, name));
  return DOCX.read(b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength));
}

const questions = await read(FILES.questions);
const script = await read(FILES.script);
const answers = await read(FILES.answers);

/* strictSource — 관리자 화면(admin-set-import.html)과 같은 잣대로 짓는다. 이게 없으면
   명령줄로 지은 팩만 조용히 느슨해진다: 문서에 없는 보기·정답에서 역산한 타일이
   들어간 채로 assets/set<N>.js 에 박히고, 그건 화면에서는 저장조차 막히는 팩이다. */
/* 듣기 화면의 화자 사진 — 배역 매니페스트(tts-voices-set12exam-11labs.json)를 보고
   목소리 성별·인원에 맞춘 것이다. 이게 없으면 듣기 1·2 모듈만 사진 없이 뜬다. */
const listeningImages = JSON.parse(fs.readFileSync(path.join(SG2, 'config/set12-listening-images.json'), 'utf8'));

const out = IMPORT.build({ code: 'SET 12', questions, script, answers, listeningImages, strictSource: true });
const stop = out.gates.filter((g) => g.level === 'stop');
if (stop.length) {
  stop.forEach((g) => console.error('STOP [' + g.scope + '] ' + g.message));
  process.exit(1);
}
out.gates.forEach((g) => console.warn('warn [' + g.scope + '] ' + g.message));

const pack = out.pack;
pack.importedAt = IMPORTED_AT;
if (pack.summary) pack.summary.sources = [FILES.questions, FILES.script, FILES.answers];

fs.writeFileSync(
  path.join(SG2, 'assets/set12.js'),
  '/* Generated by tools/build_set12.mjs (same code path as admin-set-import.html).\n'
    + '   Do not edit by hand — fix the document and build again. */\n'
    + 'window.SMEAG_SET12 = ' + JSON.stringify(pack, null, 2) + ';\n\n'
    + "if (window.SG_SET_IMPORT && typeof window.SG_SET_IMPORT.withHelpers === 'function') {\n"
    + '  window.SG_SET_IMPORT.withHelpers(window.SMEAG_SET12);\n'
    + '}\n'
);

const picDir = path.join(SG2, 'media/pictures/set12');
fs.mkdirSync(picDir, { recursive: true });
let pics = 0;
for (const name of Object.keys(questions.media || {})) {
  fs.writeFileSync(path.join(picDir, name.split('/').pop()), Buffer.from(questions.media[name]));
  pics++;
}

console.log('assets/set12.js — ' + out.stats.total + ' questions '
  + JSON.stringify(out.stats.bySection) + ', ' + pics + ' pictures');
console.log('sources: ' + FOUND.dir + '\n  ' + [FILES.questions, FILES.script, FILES.answers].join('\n  '));
