/* SMEAG StudyGround — tools/set_report.mjs : 세트 하나를 지은 뒤 "안 된 것" 리포트.
 *
 * 세트는 부족해도 항상 짓는다(2026-09-15 지시). 그래서 빌더는 stop 에서 멈추지 않고,
 * 멈추던 자리의 모든 것 — 검산의 problem · check, 점수에서 뺀 문항, 디스크에 없는
 * 음성·사진, 빠진 배역표·사진표 — 을 여기서 한 장으로 적는다.
 *
 *   studyground/docs/set-reports/set<N>.md   (빌더가 매번 새로 쓴다 — 손으로 고치지 않는다)
 */
import fs from 'node:fs';
import path from 'node:path';

function mediaRefs(pack) {
  const refs = new Set();
  (function walk(v) {
    if (typeof v === 'string') { if (v.startsWith('media/')) refs.add(v); return; }
    if (Array.isArray(v)) { v.forEach(walk); return; }
    if (v && typeof v === 'object') Object.values(v).forEach(walk);
  })(pack.sections);
  return [...refs];
}

/**
 * @param {{ setNo:number, sg2:string, out:{pack,gates,stats}, sources:string[] }} o
 * @return {{ file:string, markdown:string, counts:Object }}
 */
export function writeSetReport(o) {
  const { setNo, sg2, out, sources } = o;
  const pack = out.pack;
  const S = 'set' + setNo;
  const report = pack.report || { problems: [], checks: [], unscored: [] };

  const missingMedia = mediaRefs(pack).filter((r) => !fs.existsSync(path.join(sg2, r)));
  const missingAudio = missingMedia.filter((r) => r.startsWith('media/audio/'));
  const missingPics = missingMedia.filter((r) => !r.startsWith('media/audio/'));

  const noSpeakerPic = [];
  const listening = pack.sections.find((s) => s.id === 'listening');
  (listening ? listening.modules : []).forEach((m) => m.blocks.forEach((b) => (b.questions || []).forEach((q) => {
    if (!q.image && !b.image) noSpeakerPic.push(q.id);
  })));

  const noFaces = [];
  pack.sections.filter((s) => s.id === 'writing').forEach((sec) => sec.modules.forEach((m) => m.blocks.forEach((b) =>
    (b.questions || []).forEach((q) => {
      if (q.kind === 'discussion' && !q.professorImage) noFaces.push(q.id);
    }))));

  const files = [
    ['tts-voices-set' + setNo + 'exam-11labs.json', 'voice cast (make it with: sh tools/make_set_audio.sh ' + setNo + ')'],
    ['config/' + S + '-listening-images.json', 'listening speaker pictures (same command)'],
    ['config/offline.' + S + '.json', 'offline download list (python3 tools/build_offline_manifest.py)']
  ].filter(([f]) => !fs.existsSync(path.join(sg2, f)));

  /* 음성 받아쓰기 대조(tts_multivoice.py 끝의 audio gate) 결과. 통과 기록이 없으면 FAIL 이다 —
     게이트는 실패한 음원의 기준을 적지 않는다. WARN 은 사람이 한 번 들어 볼 것. */
  const castPath = path.join(sg2, 'tts-voices-set' + setNo + 'exam-11labs.json');
  const idxPath = path.join(sg2, 'media/audio', S, '.audio-index.verify-manifest.tts.json');
  const audioFail = [], audioListen = [];
  if (fs.existsSync(castPath)) {
    const idx = fs.existsSync(idxPath) ? (JSON.parse(fs.readFileSync(idxPath, 'utf8')).items || {}) : {};
    (JSON.parse(fs.readFileSync(castPath, 'utf8')).items || []).forEach((it) => {
      const s = (idx[it.id] || {}).stt;
      if (!s || s.verdict === 'FAIL') {
        audioFail.push('`' + it.out + '` — ' + (s ? s.reason : 'no passing speech check against the script'));
      } else if (s.verdict === 'WARN') {
        audioListen.push('`' + it.out + '` — ' + s.reason);
      }
    });
  }

  const st = out.stats;
  const L = [];
  L.push('# SET ' + setNo + ' — build report', '');
  L.push('Generated by `tools/build_set' + setNo + '.mjs`. The set is always built; this page lists what did not work.', '');
  L.push('Sources: ' + (sources || []).map((s) => '`' + s + '`').join(' · '), '');
  L.push('| | |', '|---|---|');
  L.push('| Questions | ' + st.total + ' (R ' + st.bySection.reading + ' · L ' + st.bySection.listening
    + ' · W ' + st.bySection.writing + ' · S ' + st.bySection.speaking + ') |');
  L.push('| Not scored | ' + report.unscored.length + ' |');
  L.push('| Problems | ' + report.problems.length + ' |');
  L.push('| Checks | ' + report.checks.length + ' |');
  L.push('| Audio files missing | ' + missingAudio.length + ' |');
  L.push('| Pictures missing | ' + missingPics.length + ' |');
  L.push('| Audio failing the speech check | ' + audioFail.length + ' |');
  L.push('| Audio to listen to once | ' + audioListen.length + ' |', '');

  const section = (title, items, fmt) => {
    L.push('## ' + title, '');
    if (!items.length) { L.push('None.', ''); return; }
    items.forEach((x) => L.push('- ' + fmt(x)));
    L.push('');
  };
  section('Questions not scored', report.unscored, (u) => '`' + u.id + '` — ' + u.reason);
  section('Problems (these used to stop the build)', report.problems, (m) => m);
  section('Checks', report.checks, (m) => m);
  section('Audio files the set points at but are not on disk', missingAudio, (m) => '`' + m + '`');
  section('Pictures the set points at but are not on disk', missingPics, (m) => '`' + m + '`');
  section('Audio that fails the speech check (students hear it, but it does not match the script)', audioFail, (m) => m);
  section('Audio a person should listen to once (small differences)', audioListen, (m) => m);
  section('Listening questions without a speaker picture', noSpeakerPic.length ? [noSpeakerPic.join(', ')] : [], (m) => m);
  section('Academic discussion without faces', noFaces, (m) => '`' + m + '` — shows initials instead of photos (config/' + S + '-writing-images.json)');
  section('Files not made yet', files, ([f, why]) => '`' + f + '` — ' + why);

  const markdown = L.join('\n');
  const file = path.join(path.dirname(sg2), 'docs', 'set-reports', S + '.md');
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, markdown);
  return {
    file, markdown,
    counts: {
      unscored: report.unscored.length, problems: report.problems.length, checks: report.checks.length,
      missingAudio: missingAudio.length, missingPics: missingPics.length, noSpeakerPic: noSpeakerPic.length,
      audioFail: audioFail.length, audioListen: audioListen.length
    }
  };
}
